#print(''' Sprawdź i wyjaśnij działanie następujących instrukcji:''')

a = int(3.0)
print(a)
print(type(a))
b = float(3)
print(b)
print(type(b))
c = float("3")
print(c)
print(type(c))
d = str(12.4)
print(d)
print(type(d))
e = bool(0)
print(e)
print(type(e))